---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install apt packages
  apt:
    pkg: "{{ install_apt_packages }}"
    state: present
    update_cache: false

- name: Install pip packages
  pip:
    name: "{{ install_pip_packages }}"
    state: present
